# Generated by Django 2.0.7 on 2018-08-16 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='photo',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
